version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: team3
      MYSQL_DATABASE: spotify_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: team3
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "true"]

  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=team3
      - DB_NAME=spotify_db
      - PYTHONPATH=/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
      driver: bridge
