services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: team3
      MYSQL_DATABASE: tunetalk
      MYSQL_USER: tune
      MYSQL_PASSWORD: talk

